version: '3'

services:
  productdatabase:
    image: mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: adminer
    ports:
      - '8081:8080'