"""Dodato polje quantity za vezu Prozivod-Narudzbina

Revision ID: 338eb13d76f3
Revises: d57ec8dcb062
Create Date: 2023-08-22 17:47:38.818437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338eb13d76f3'
down_revision = 'd57ec8dcb062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productorder', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productorder', 'quantity')
    # ### end Alembic commands ###
