"""Dodato polje za drzaca porudzbine u formi emaila

Revision ID: bb70851ba81a
Revises: 338eb13d76f3
Create Date: 2023-08-22 19:30:16.337371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb70851ba81a'
down_revision = '338eb13d76f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'user')
    # ### end Alembic commands ###
